import 'dart:convert';

import 'package:avaremp/aircraft/aircraft.dart';
import 'package:avaremp/ai/ai_credentials.dart';
import 'package:avaremp/ai/ai_settings_screen.dart';
import 'package:avaremp/constants.dart';
import 'package:avaremp/data/user_database_helper.dart';
import 'package:avaremp/logbook/log_entry.dart';
import 'package:avaremp/plan/plan_route.dart';
import 'package:avaremp/storage.dart';
import 'package:avaremp/utils/toast.dart';
import 'package:avaremp/weather/winds_cache.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:latlong2/latlong.dart' show LatLng;
import 'package:flutter_material_design_icons/flutter_material_design_icons.dart';

class AiScreen extends StatefulWidget {
  const AiScreen({super.key});

  @override
  AiScreenState createState() => AiScreenState();
}

class AiScreenState extends State<AiScreen> {

  bool _clear = false;
  static const _credentials = AiCredentials();
  AiConfig _config = const AiConfig(baseUrl: '', apiKey: '', model: '');
  bool _isSending = false;
  final TextEditingController _editingController = TextEditingController();

  bool includePlan = false;
  bool includeAircraft = false;
  bool includeLogbook = false;
  bool includeWeather = false;

  List<(int, String, String)> _allQueries = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadConfig();
    _loadQueries();
  }

  Future<void> _loadConfig() async {
    final config = await _credentials.read();
    if (mounted) {
      setState(() => _config = config);
    }
  }

  Future<void> _openSettings() async {
    await Navigator.push(
      context,
      MaterialPageRoute(builder: (_) => const AiSettingsScreen()),
    );
    await _loadConfig();
  }

  Future<void> _loadQueries() async {
    final queries = await UserDatabaseHelper.db.getAllAiQueries();
    if (mounted) {
      setState(() {
        _allQueries = queries;
        _isLoading = false;
        if (_allQueries.isNotEmpty && _editingController.text.isEmpty) {
          _editingController.text = _allQueries[0].$2;
        }
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const Center(child: CircularProgressIndicator());
    }
    return _makeContent();
  }

  Widget _makeContent() {
    String disclaimer = "Responses are generated by an AI model and may not be accurate or reliable. Do not use this when life, health, property are at stake.";

    if (_clear) {
      _editingController.text = "";
      _clear = false;
    }

    Future<String> processQuery() async {
      String myQuery = _editingController.text;
      if(myQuery.isEmpty) {
        return "Please enter a question first";
      }
      if(!_config.isUsable) {
        return "No AI provider is configured. Tap the settings icon to add your provider URL, API key and model.";
      }
      if(myQuery.length > 8192) {
        return "Question length must be less than 8192 characters";
      }

      // Assemble the user message from the question plus any opted-in context.
      final StringBuffer content = StringBuffer(myQuery);

      if(includeAircraft) {
        List<Aircraft> aircraft = await UserDatabaseHelper.db.getAllAircraft();
        if(aircraft.isNotEmpty) {
          Aircraft ac = aircraft.first;
          content.write("\n\nUse aircraft ${ac.tail} and make/mode ${ac.type}");
        }
      }
      if(includeLogbook) {
        List<LogEntry> entries = await UserDatabaseHelper.db.getAllLogbook();
        if(entries.isNotEmpty) {
          content.write("\n\nLast 50 log book entries are:\n");
          content.write("${entries.first.toMap().keys.join(",")}\n");
          for(int i = 0; i < entries.length && i < 50; i++) {
            content.write("${entries[i].toMap().values.join(",")}\n");
          }
        }
      }
      if(includeWeather) {
        PlanRoute route = Storage().route;
        if (route.isNotEmpty) {
          LatLng start = route.getAllDestinations().first.coordinate;
          LatLng end = route.getAllDestinations().last.coordinate;
          String? windsStart = WindsCache.getWindsAtAll(start, 6);
          String? windsEnd = WindsCache.getWindsAtAll(end, 6);
          if (windsStart != null) {
            content.write("\n\nWinds at departure:\n$windsStart\n");
          }
          if (windsEnd != null) {
            content.write("Winds at destination:\n$windsEnd\n");
          }
        }
      }
      if(includePlan) {
        PlanRoute route = Storage().route;
        if(route.isNotEmpty) {
          content.write("\n\nPlan is: ${route.toString()}\n");
        }
      }

      String ret = "Unable to get an answer.";
      try {
        final response = await http.post(
          _config.chatCompletionsUri,
          headers: {
            'Content-Type': 'application/json',
            if (_config.apiKey.isNotEmpty)
              'Authorization': 'Bearer ${_config.apiKey}',
          },
          body: jsonEncode({
            'model': _config.model,
            'messages': [
              {
                'role': 'system',
                'content':
                    'You are an aviation assistant for pilots. Be concise and accurate.'
              },
              {'role': 'user', 'content': content.toString()},
            ],
          }),
        );
        if (response.statusCode != 200) {
          ret = "Provider error: HTTP ${response.statusCode}. Check your AI provider settings.";
        } else {
          final decoded = jsonDecode(utf8.decode(response.bodyBytes));
          final text = decoded['choices']?[0]?['message']?['content'];
          if (text is String && text.trim().isNotEmpty) {
            ret = text.trim();
          } else {
            ret = "Error: no response from the provider.";
          }
        }
      }
      catch(e) {
        ret = "Internet connection needed, or the provider is unreachable.";
      }
      await UserDatabaseHelper.db.insertAiQueries(myQuery, ret);
      _loadQueries();
      return ret;
    }

    Widget questions = StatefulBuilder(builder: (BuildContext context, StateSetter setState1) =>
      Drawer(
        child: Column(
          children: [
            Container(
              width: double.infinity,
              padding: const EdgeInsets.fromLTRB(16, 48, 16, 16),
              color: Theme.of(context).colorScheme.primaryContainer,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(Icons.history, size: 32, color: Theme.of(context).colorScheme.onPrimaryContainer),
                  const SizedBox(height: 8),
                  Text(
                    "Question History",
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: Theme.of(context).colorScheme.onPrimaryContainer,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    "${_allQueries.length} saved questions",
                    style: TextStyle(
                      fontSize: 12,
                      color: Theme.of(context).colorScheme.onPrimaryContainer.withAlpha(180),
                    ),
                  ),
                ],
              ),
            ),
            Expanded(
              child: _allQueries.isEmpty
                ? Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(Icons.chat_bubble_outline, size: 48, color: Theme.of(context).colorScheme.outline),
                        const SizedBox(height: 12),
                        Text("No questions yet", style: TextStyle(color: Theme.of(context).colorScheme.outline)),
                      ],
                    ),
                  )
                : ListView.separated(
                    padding: const EdgeInsets.symmetric(vertical: 8),
                    separatorBuilder: (_, __) => const Divider(height: 1),
                    itemCount: _allQueries.length,
                    itemBuilder: (context, index) {
                      final value = _allQueries[index];
                      int id = value.$1;
                      String query = value.$2;
                      String answer = value.$3;
                      return ListTile(
                        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                        title: Text(
                          query,
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                          style: const TextStyle(fontSize: 14),
                        ),
                        subtitle: Padding(
                          padding: const EdgeInsets.only(top: 8),
                          child: Wrap(
                            spacing: 8,
                            children: [
                              TextButton.icon(
                                onPressed: () {
                                  _editingController.text = query;
                                  Navigator.pop(context);
                                },
                                icon: const Icon(Icons.edit, size: 16),
                                label: const Text("Use"),
                                style: TextButton.styleFrom(
                                  padding: const EdgeInsets.symmetric(horizontal: 8),
                                  minimumSize: Size.zero,
                                  tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                                ),
                              ),
                              if(answer.isNotEmpty)
                                TextButton.icon(
                                  onPressed: () {
                                    _editingController.text = answer;
                                    Navigator.pop(context);
                                  },
                                  icon: const Icon(Icons.visibility, size: 16),
                                  label: const Text("Answer"),
                                  style: TextButton.styleFrom(
                                    padding: const EdgeInsets.symmetric(horizontal: 8),
                                    minimumSize: Size.zero,
                                    tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                                  ),
                                ),
                              TextButton.icon(
                                onPressed: () =>
                                  UserDatabaseHelper.db.deleteAiQuery(id).then((_) {
                                    setState1(() {
                                      _allQueries.removeWhere((element) => element.$1 == id);
                                    });
                                  }),
                                icon: const Icon(Icons.delete_outline, size: 16),
                                label: const Text("Delete"),
                                style: TextButton.styleFrom(
                                  foregroundColor: Theme.of(context).colorScheme.error,
                                  padding: const EdgeInsets.symmetric(horizontal: 8),
                                  minimumSize: Size.zero,
                                  tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                                ),
                              ),
                            ],
                          ),
                        ),
                      );
                    },
                  ),
            ),
          ],
        ),
      ),
    );

    final GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>();
    
    return Scaffold(
      endDrawer: questions,
      key: scaffoldKey,
      appBar: AppBar(
        backgroundColor: Constants.appBarBackgroundColor,
        title: Row(
          children: [
            Icon(MdiIcons.robot, size: 24),
            const SizedBox(width: 8),
            const Text("Flight Intelligence"),
          ],
        ),
        actions: [
          IconButton(
            onPressed: _isSending ? null : _openSettings,
            icon: const Icon(Icons.settings),
            tooltip: "AI provider settings",
          ),
          IconButton(
            onPressed: _isSending ? null : () => scaffoldKey.currentState!.openEndDrawer(),
            icon: const Icon(Icons.history),
            tooltip: "Question history",
          ),
          Tooltip(
            showDuration: const Duration(seconds: 30),
            triggerMode: TooltipTriggerMode.tap,
            message: "Ask AvareX anything about flying (Internet required).\n\nAdd context chips below to include:\n• Logbook - Your 50 most recent entries\n• Aircraft - Details from your first aircraft\n• Plan - Your current flight plan\n• Weather - Winds aloft data\n\nTap history icon for previous questions.",
            child: const Padding(
              padding: EdgeInsets.symmetric(horizontal: 8),
              child: Icon(Icons.help_outline),
            ),
          ),
        ],
      ),
      body: Column(
        children: [
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(12),
            color: Theme.of(context).colorScheme.errorContainer.withAlpha(80),
            child: Row(
              children: [
                Icon(Icons.warning_amber, size: 16, color: Theme.of(context).colorScheme.error),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    disclaimer,
                    style: TextStyle(fontSize: 11, color: Theme.of(context).colorScheme.onErrorContainer),
                  ),
                ),
              ],
            ),
          ),
          Expanded(
            child: Card(
              margin: const EdgeInsets.all(8),
              child: Column(
                children: [
                  Expanded(
                    child: Stack(
                      children: [
                        TextField(
                          controller: _editingController,
                          autofocus: true,
                          enabled: !_isSending,
                          enableInteractiveSelection: true,
                          maxLines: null,
                          expands: true,
                          textAlignVertical: TextAlignVertical.top,
                          decoration: InputDecoration(
                            hintText: "Ask me anything about aviation...",
                            border: InputBorder.none,
                            contentPadding: const EdgeInsets.all(16),
                            hintStyle: TextStyle(color: Theme.of(context).colorScheme.outline),
                          ),
                        ),
                        if (_isSending)
                          Container(
                            color: Theme.of(context).colorScheme.surface.withAlpha(200),
                            child: const Center(
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  CircularProgressIndicator(),
                                  SizedBox(height: 16),
                                  Text("Thinking..."),
                                ],
                              ),
                            ),
                          ),
                      ],
                    ),
                  ),
                  const Divider(height: 1),
                  Padding(
                    padding: const EdgeInsets.all(8),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: [
                        TextButton.icon(
                          onPressed: _isSending ? null : () {
                            setState(() {
                              _clear = true;
                            });
                          },
                          icon: const Icon(Icons.clear, size: 18),
                          label: const Text("Clear"),
                        ),
                        const SizedBox(width: 8),
                        FilledButton.icon(
                          onPressed: _isSending ? null : () async {
                            setState(() {
                              _isSending = true;
                            });

                            String responseText;
                            try {
                              responseText = await processQuery();
                            } catch(e) {
                              responseText = e.toString();
                            }
                            setState(() {
                              _isSending = false;
                              _editingController.text = responseText;
                            });
                          },
                          icon: const Icon(Icons.send, size: 18),
                          label: const Text("Ask"),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
          _buildContextSection(),
        ],
      ),
    );
  }

  Widget _buildContextSection() {
    return StatefulBuilder(
      builder: (context, setLocalState) {
        Widget contextIcon({
          required String label,
          required IconData icon,
          required bool selected,
          required VoidCallback onTap,
          required String tooltip,
        }) {
          final scheme = Theme.of(context).colorScheme;
          return Tooltip(
            message: tooltip,
            child: IconButton(
              onPressed: _isSending
                  ? null
                  : () {
                      onTap();
                      setLocalState(() {});
                    },
              icon: Icon(icon, size: 18),
              color: selected ? scheme.onPrimaryContainer : scheme.outline,
              style: IconButton.styleFrom(
                backgroundColor: selected ? scheme.primaryContainer : Colors.transparent,
                tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                minimumSize: const Size(36, 36),
                padding: EdgeInsets.zero,
              ),
            ),
          );
        }

        void toggleWithToast({
          required String sourceLabel,
          required IconData icon,
          required bool newSelected,
        }) {
          final message = newSelected
              ? "Context from $sourceLabel included in the query"
              : "Context from $sourceLabel removed from the query";
          Toast.showToast(context, message, Icon(icon, size: 18), 2);
        }

        return Card(
          margin: const EdgeInsets.all(8),
          child: Padding(
            padding: const EdgeInsets.all(12),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Icon(Icons.add_circle_outline, size: 16, color: Theme.of(context).colorScheme.primary),
                    const SizedBox(width: 6),
                    Text(
                      "Include Context",
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.w600,
                        color: Theme.of(context).colorScheme.primary,
                      ),
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Align(
                        alignment: Alignment.centerRight,
                        child: Wrap(
                          spacing: 6,
                          runSpacing: 6,
                          children: [
                            contextIcon(
                              label: "Logbook",
                              icon: Icons.notes,
                              selected: includeLogbook,
                              tooltip: "Include your 50 most recent logbook entries",
                              onTap: () {
                                includeLogbook = !includeLogbook;
                                toggleWithToast(
                                  sourceLabel: "logbook",
                                  icon: Icons.notes,
                                  newSelected: includeLogbook,
                                );
                              },
                            ),
                            contextIcon(
                              label: "Aircraft",
                              icon: MdiIcons.airplane,
                              selected: includeAircraft,
                              tooltip: "Include details from your first aircraft",
                              onTap: () {
                                includeAircraft = !includeAircraft;
                                toggleWithToast(
                                  sourceLabel: "aircraft",
                                  icon: MdiIcons.airplane,
                                  newSelected: includeAircraft,
                                );
                              },
                            ),
                            contextIcon(
                              label: "Plan",
                              icon: Icons.route,
                              selected: includePlan,
                              tooltip: "Include your current flight plan",
                              onTap: () {
                                includePlan = !includePlan;
                                toggleWithToast(
                                  sourceLabel: "plan",
                                  icon: Icons.route,
                                  newSelected: includePlan,
                                );
                              },
                            ),
                            contextIcon(
                              label: "Weather",
                              icon: Icons.cloud,
                              selected: includeWeather,
                              tooltip: "Include winds aloft from departure and destination",
                              onTap: () {
                                includeWeather = !includeWeather;
                                toggleWithToast(
                                  sourceLabel: "weather",
                                  icon: Icons.cloud,
                                  newSelected: includeWeather,
                                );
                              },
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  static void teleportToAiScreen(BuildContext context, String query) {
    if(Constants.shouldShowAi) {
      UserDatabaseHelper.db.insertAiQueries(query, '').then((value) {
        if(context.mounted) {
          Navigator.pushNamed(context, "/ai");
        }
      });
    }
  }
}
