import 'package:avaremp/aircraft/aircraft.dart';
import 'package:avaremp/constants.dart';
import 'package:avaremp/data/user_database_helper.dart';
import 'package:avaremp/logbook/log_entry.dart';
import 'package:avaremp/plan/plan_route.dart';
import 'package:avaremp/services/login_screen.dart';
import 'package:avaremp/storage.dart';
import 'package:avaremp/weather/winds_cache.dart';
import 'package:firebase_ai/firebase_ai.dart';
import 'package:flutter/material.dart';
import 'package:latlong2/latlong.dart' show LatLng;
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';

class AiScreen extends StatefulWidget {
  const AiScreen({super.key});

  @override
  AiScreenState createState() => AiScreenState();
}

class AiScreenState extends State<AiScreen> {

  bool _clear = false;
  bool _asked = false;
  final _model = FirebaseAI.vertexAI().generativeModel(model: 'gemini-2.5-pro', tools: [Tool.googleSearch()]);
  bool _isSending = false;
  final TextEditingController _editingController = TextEditingController();

  bool includePlan = false;
  bool includeAircraft = false;
  bool includeLogbook = false;
  bool includeWeather = false;

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: UserDatabaseHelper.db.getAllAiQueries(),
      builder: (BuildContext context, AsyncSnapshot<List<(int, String, String)>?> snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return _makeContent(snapshot.data);
        }
        return const Center(child: CircularProgressIndicator());
      },
    );
  }

  Widget _makeContent(List<(int, String, String)>? data) {
    String disclaimer = "Responses are generated by an AI model and may not be accurate or reliable. Do not use this when life, health, property are at stake.";
    data ??= [];
    List<(int, String, String)> allQueries = data;

    if(_isSending) {
      // Keep current text while sending
    } else if(_asked) {
      _asked = false;
    } else if (_clear) {
      _editingController.text = "";
      _clear = false;
    } else if (data.isNotEmpty) {
      _editingController.text = data[0].$2;
    }

    Widget contextChip(String label, IconData icon, bool selected, VoidCallback onTap, String tooltip) {
      return Tooltip(
        message: tooltip,
        child: FilterChip(
          avatar: Icon(icon, size: 18, color: selected ? Theme.of(context).colorScheme.onPrimaryContainer : Theme.of(context).colorScheme.outline),
          label: Text(label),
          selected: selected,
          onSelected: _isSending ? null : (_) => onTap(),
          selectedColor: Theme.of(context).colorScheme.primaryContainer,
          showCheckmark: false,
        ),
      );
    }

    Widget contextSection = Card(
      margin: const EdgeInsets.all(8),
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(Icons.add_circle_outline, size: 16, color: Theme.of(context).colorScheme.primary),
                const SizedBox(width: 6),
                Text(
                  "Include Context",
                  style: TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.w600,
                    color: Theme.of(context).colorScheme.primary,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 10),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                contextChip("Logbook", Icons.notes, includeLogbook, () => setState(() => includeLogbook = !includeLogbook), "Include your 50 most recent logbook entries"),
                contextChip("Aircraft", MdiIcons.airplane, includeAircraft, () => setState(() => includeAircraft = !includeAircraft), "Include details from your first aircraft"),
                contextChip("Plan", Icons.route, includePlan, () => setState(() => includePlan = !includePlan), "Include your current flight plan"),
                contextChip("Weather", Icons.cloud, includeWeather, () => setState(() => includeWeather = !includeWeather), "Include winds aloft from departure and destination"),
              ],
            ),
          ],
        ),
      ),
    );

    Future<String> processQuery() async {
      String myQuery = _editingController.text;
      if(myQuery.isEmpty) {
        return "Please enter a question first";
      }
      final prompt = TextPart(myQuery);
      List<Part> parts = [];
      parts.add(prompt);

      if(includeAircraft) {
        List<Aircraft> aircraft = await UserDatabaseHelper.db.getAllAircraft();
        if(aircraft.isNotEmpty) {
          Aircraft ac = aircraft.first;
          final acText = "Use aircraft ${ac.tail} and make/mode ${ac.type}";
          parts.add(TextPart(acText));
        }
      }
      if(includeLogbook) {
        List<LogEntry> entries = await UserDatabaseHelper.db.getAllLogbook();
        if(entries.isNotEmpty) {
          String logText = "Last 50 log book entries are:\n";
          logText += "${entries.first.toMap().keys.join(",")}\n";
          for(int i = 0; i < entries.length && i < 50; i++) {
            logText += "${entries[i].toMap().values.join(",")}\n";
          }
          parts.add(TextPart(logText));
        }
      }
      if(includeWeather) {
        String weatherText = "";
        PlanRoute route = Storage().route;
        if (route.isNotEmpty) {
          LatLng start = route.getAllDestinations().first.coordinate;
          LatLng end = route.getAllDestinations().last.coordinate;
          String? windsStart = WindsCache.getWindsAtAll(start, 6);
          String? windsEnd = WindsCache.getWindsAtAll(end, 6);
          if (windsStart != null) {
            weatherText += "Winds at departure:\n$windsStart\n";
          }
          if (windsEnd != null) {
            weatherText += "Winds at destination:\n$windsStart\n";
          }
          parts.add(TextPart(weatherText));
        }
      }
      if(includePlan) {
        PlanRoute route = Storage().route;
        if(route.isNotEmpty) {
          String planText = "Plan is: ${route.toString()}\n";
          parts.add(TextPart(planText));
        }
      }
      String ret = "Unable to get an answer.";
      try {
        final query = Content.multi(parts);
        final responseT = await _model.countTokens([query]);
        final totalTokens = responseT.totalTokens;
        if(myQuery.length > 256) {
          ret = "Question length must be less than 256 characters";
        }
        else if (totalTokens > 10000) {
          ret = "Please reduce the amount of context included to 10000 tokens - total tokens $totalTokens";
        }
        else {
          final response = await _model.generateContent([query]);
          if (response.text == null) {
            ret = "Error: no response from the server";
          }
          else {
            ret = response.text!;
          }
        }
      }
      catch(e) {
        ret = "Internet connection needed.";
      }
      await UserDatabaseHelper.db.insertAiQueries(myQuery, ret);
      return ret;
    }

    Widget questions = StatefulBuilder(builder: (BuildContext context, StateSetter setState1) =>
      Drawer(
        child: Column(
          children: [
            Container(
              width: double.infinity,
              padding: const EdgeInsets.fromLTRB(16, 48, 16, 16),
              color: Theme.of(context).colorScheme.primaryContainer,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(Icons.history, size: 32, color: Theme.of(context).colorScheme.onPrimaryContainer),
                  const SizedBox(height: 8),
                  Text(
                    "Question History",
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: Theme.of(context).colorScheme.onPrimaryContainer,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    "${allQueries.length} saved questions",
                    style: TextStyle(
                      fontSize: 12,
                      color: Theme.of(context).colorScheme.onPrimaryContainer.withAlpha(180),
                    ),
                  ),
                ],
              ),
            ),
            Expanded(
              child: allQueries.isEmpty
                ? Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(Icons.chat_bubble_outline, size: 48, color: Theme.of(context).colorScheme.outline),
                        const SizedBox(height: 12),
                        Text("No questions yet", style: TextStyle(color: Theme.of(context).colorScheme.outline)),
                      ],
                    ),
                  )
                : ListView.separated(
                    padding: const EdgeInsets.symmetric(vertical: 8),
                    separatorBuilder: (_, __) => const Divider(height: 1),
                    itemCount: allQueries.length,
                    itemBuilder: (context, index) {
                      final value = allQueries[index];
                      int id = value.$1;
                      String query = value.$2;
                      String answer = value.$3;
                      return ListTile(
                        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                        title: Text(
                          query,
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                          style: const TextStyle(fontSize: 14),
                        ),
                        subtitle: Padding(
                          padding: const EdgeInsets.only(top: 8),
                          child: Wrap(
                            spacing: 8,
                            children: [
                              TextButton.icon(
                                onPressed: () {
                                  setState(() {
                                    _editingController.text = query;
                                    _asked = true;
                                    Navigator.pop(context);
                                  });
                                },
                                icon: const Icon(Icons.edit, size: 16),
                                label: const Text("Use"),
                                style: TextButton.styleFrom(
                                  padding: const EdgeInsets.symmetric(horizontal: 8),
                                  minimumSize: Size.zero,
                                  tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                                ),
                              ),
                              if(answer.isNotEmpty)
                                TextButton.icon(
                                  onPressed: () {
                                    setState(() {
                                      _editingController.text = answer;
                                      _asked = true;
                                      Navigator.pop(context);
                                    });
                                  },
                                  icon: const Icon(Icons.visibility, size: 16),
                                  label: const Text("Answer"),
                                  style: TextButton.styleFrom(
                                    padding: const EdgeInsets.symmetric(horizontal: 8),
                                    minimumSize: Size.zero,
                                    tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                                  ),
                                ),
                              TextButton.icon(
                                onPressed: () =>
                                  UserDatabaseHelper.db.deleteAiQuery(id).then((_) {
                                    setState1(() {
                                      allQueries.removeWhere((element) => element.$1 == id);
                                    });
                                  }),
                                icon: const Icon(Icons.delete_outline, size: 16),
                                label: const Text("Delete"),
                                style: TextButton.styleFrom(
                                  foregroundColor: Theme.of(context).colorScheme.error,
                                  padding: const EdgeInsets.symmetric(horizontal: 8),
                                  minimumSize: Size.zero,
                                  tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                                ),
                              ),
                            ],
                          ),
                        ),
                      );
                    },
                  ),
            ),
          ],
        ),
      ),
    );

    final GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>();
    
    return Scaffold(
      endDrawer: questions,
      key: scaffoldKey,
      appBar: AppBar(
        backgroundColor: Constants.appBarBackgroundColor,
        title: Row(
          children: [
            Icon(MdiIcons.robot, size: 24),
            const SizedBox(width: 8),
            const Text("Flight Intelligence"),
          ],
        ),
        actions: [
          IconButton(
            onPressed: _isSending ? null : () => scaffoldKey.currentState!.openEndDrawer(),
            icon: const Icon(Icons.history),
            tooltip: "Question history",
          ),
          Tooltip(
            showDuration: const Duration(seconds: 30),
            triggerMode: TooltipTriggerMode.tap,
            message: "Ask AvareX anything about flying (Internet required).\n\nAdd context chips below to include:\n• Logbook - Your 50 most recent entries\n• Aircraft - Details from your first aircraft\n• Plan - Your current flight plan\n• Weather - Winds aloft data\n\nTap history icon for previous questions.",
            child: const Padding(
              padding: EdgeInsets.symmetric(horizontal: 8),
              child: Icon(Icons.help_outline),
            ),
          ),
        ],
      ),
      body: Column(
        children: [
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(12),
            color: Theme.of(context).colorScheme.errorContainer.withAlpha(80),
            child: Row(
              children: [
                Icon(Icons.warning_amber, size: 16, color: Theme.of(context).colorScheme.error),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    disclaimer,
                    style: TextStyle(fontSize: 11, color: Theme.of(context).colorScheme.onErrorContainer),
                  ),
                ),
              ],
            ),
          ),
          Expanded(
            child: Card(
              margin: const EdgeInsets.all(8),
              child: Column(
                children: [
                  Expanded(
                    child: Stack(
                      children: [
                        TextField(
                          controller: _editingController,
                          autofocus: true,
                          enabled: !_isSending,
                          enableInteractiveSelection: true,
                          maxLines: null,
                          expands: true,
                          textAlignVertical: TextAlignVertical.top,
                          decoration: InputDecoration(
                            hintText: "Ask me anything about aviation...",
                            border: InputBorder.none,
                            contentPadding: const EdgeInsets.all(16),
                            hintStyle: TextStyle(color: Theme.of(context).colorScheme.outline),
                          ),
                        ),
                        if (_isSending)
                          Container(
                            color: Theme.of(context).colorScheme.surface.withAlpha(200),
                            child: const Center(
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  CircularProgressIndicator(),
                                  SizedBox(height: 16),
                                  Text("Thinking..."),
                                ],
                              ),
                            ),
                          ),
                      ],
                    ),
                  ),
                  const Divider(height: 1),
                  Padding(
                    padding: const EdgeInsets.all(8),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: [
                        TextButton.icon(
                          onPressed: _isSending ? null : () {
                            setState(() {
                              _clear = true;
                            });
                          },
                          icon: const Icon(Icons.clear, size: 18),
                          label: const Text("Clear"),
                        ),
                        const SizedBox(width: 8),
                        FilledButton.icon(
                          onPressed: _isSending ? null : () async {
                            setState(() {
                              _isSending = true;
                            });

                            String responseText;
                            try {
                              responseText = await processQuery();
                            } catch(e) {
                              responseText = e.toString();
                            }
                            setState(() {
                              _isSending = false;
                              _asked = true;
                              _editingController.text = responseText;
                            });
                          },
                          icon: const Icon(Icons.send, size: 18),
                          label: const Text("Ask"),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
          contextSection,
        ],
      ),
    );
  }

  static void teleportToAiScreen(BuildContext context, String query) {
    if(Constants.shouldShowProServices) {
      UserDatabaseHelper.db.insertAiQueries(query, '').then((value) {
        if(context.mounted) {
          LoginScreenState.showPaywall(context, "/ai");
        }
      });
    }
  }
}
