name: avarex 
version: 0.0.78
icon: assets/images/logo.png
summary: AvareX Flight Support 
description: AvareX provide FAA charts, plates, airport data, weather, air traffic over ADS-B, and lets you create and file flight plans. 

confinement: strict
base: core22
grade: stable

apps:
  avarex:
    command: AvareX 
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - network
      - location-observe
      - network-bind
      - home
      - audio-playback
 
parts:

  # for file import
  zenity-integration:
    plugin: nil
    stage-snaps:
      - zenity-integration

  avarex:
    
    override-pull: |
      set -eux
      rm -rf $SNAPCRAFT_PROJECT_DIR/build
      snapcraftctl pull
      
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application

    build-packages: 
      - libgstreamer1.0-dev 
      - libgstreamer-plugins-base1.0-dev
    stage-packages:
      - libsqlite3-dev
