name: Android Test Build

on:
  push:
    branches:
      - main  # Adjust this to your branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.4'

      # OpenAIP Replacement Step
      - name: Find and Replace OpenAIP
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/*.dart'
          search-text: '@@___openaip_client_id__@@'
          replacement-text: ${{ secrets.OPENAIP_CLIENT_ID }}
          encoding: 'utf8'
          max-parallelism: 10

      # Install dependencies
      - name: Install project dependencies
        run: flutter pub get

      # Build APK
      - name: Build APK
        run: flutter build apk --release  # For optimized builds

      # Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release-unsigned.apk
