name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.24.4'

    - name: Replace OpenAIP placeholders
      uses: richardrigutins/replace-in-files@v2
      with:
        files: '**/*.dart'
        search-text: '@@___openaip_client_id__@@'
        replacement-text: ${{ secrets.OPENAIP_CLIENT_ID }}
        encoding: 'utf8'
        max-parallelism: 10

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Sign APK with custom keystore
      env:
        KEY_STORE: ${{ secrets.KEY_STORE }}
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        echo "$KEY_STORE" | base64 -d > release-key.jks
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore release-key.jks \
          -storepass "$KEY_STORE_PASSWORD" \
          -keypass "$KEY_PASSWORD" \
          build/app/outputs/apk/release/app-release.apk "$KEY_ALIAS"

    - name: Upload signed APK
      uses: actions/upload-artifact@v4
      with:
        name: Signed APK
        path: build/app/outputs/apk/release/app-release.apk
